import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Not from "@/components/Not";
import Slider from "@/components/Slider";
import FoodMenu from "@/components/FoodMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EpicStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex bg-slate-200 m-auto  min-h-screen flex-col items-center  ">
          <Not />
          <Navbar />
          <Slider />
          {children}
        </div>
      </body>
    </html>
  );
}
